### ISSUE TITLE
Neue API? 

### ISSUE THREAD

**Issue by UnderTheCraft** [derweili/rnk-vaccine-bot#1]
Seit ein paar Tagen kommen keine Benachrichtigungen mehr in Pushover. Auf der Website gab es zwischenzeitlich Wartungsarbeiten und nun ist das Dropdown Feld "Bereich" hinzugekommen. Möglicherweise muss diese Änderung ebenfalls im Code angepasst werden?

**Comment by derweili** [comment]
Es gab wohl einen Fehler mit dem Cronjob. Der läuft jetzt wieder. Die API werde ich nochmal prüfen und auch schauen was dieses Bereich Drop-down macht.

**Comment by derweili** [comment]
@UnderTheCraft die APIs wurden nicht geändert. Das Dropdown "Bereich" filtert nur die im "Termin-Ort" wählbaren Optionen.

**Comment by derweili** [comment]
Es könnte sein dass Pushover Notifications in ein paar Tagen erneut nicht gehen da dann die kostenfreien API Limits erreicht werden. Ich habe Script schon so angepasst dass nur eine gesammelte Pushnotification für alle Zentren geschickt wird, das wird das Erreichen der Pushover API Limits aber nur etwas verzögern.
